# Generated by Django 3.2 on 2023-02-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='text',
        ),
    ]
